---
- name: "Pip venv"
  hosts: "centos_server"
  become: true
  vars:
    app_name: "hello"
    mysql_password: "password"
    ansible_pythonr_interpreter: /usr/bin/python3
  roles:
    - nginx

  tasks:
    - name: Install required packages
      ansible.builtin.yum:
        name:
          - python3
          - python3-pip
          - python3-setuptools
          - python2-setuptools # сначала попробовть без этого модуля
          - libselinux-python3
          - python2-PyMySQL
          - mariadb-server
        state: latest
        update_cache: true

    - name: "Start mariadb"
      ansible.builtin.service:
        name: mariadb
        state: started

    - name: "Add the MySQL database"
      community.mysql.mysql_db:
        name: service_db
        state: present
        login_user: root
        login_password: "password"
        check_implicit_admin: true

    - name: "Copy python files"
      ansible.builtin.copy:
        src: files/app
        dest: /apps/{{app_name}}
        owner: vagrant # поменять на s016269
        group: vagrant # поменять на 577c7917
        mode: 0644

    - name: Install virtualenv via pip
      ansible.builtin.pip:
        name: virtualenv
        executable: pip3

    - name: Install requirements
      ansible.builtin.pip:
        requirements: /apps/{{app_name}}/app/requirements.txt
        virtualenv: /apps/{{app_name}}/venv
        virtualenv_command: /usr/bin/python3 -m venv

    - name: Copy service file
      ansible.builtin.template:
        src: service.service.j2
        dest: /etc/systemd/system/{{app_name}}.service
        owner: vagrant # поменять на s016269
        group: vagrant # поменять на 577c7917
        mode: 0644

    - name: "Start service"
      ansible.builtin.service:
        name: "{{ app_name }}"
        state: started