---
- name: "Test run"
  hosts: "localhost"
  gather_facts: true

  tasks:
  - name: "ping host"
    ansible.builtin.ping:

  - name: "Print OS"
    ansible.builtin.debug:
      msg: "Host OS is {{ansible_os_family}} {{ansible_distribution_major_version}}"